version: "3"
services:
  clef2024-longeval-cir:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
        - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
